cmake_minimum_required(VERSION 3.19)

set(PACKAGE_NAME Utils)
set(${PACKAGE_NAME}_FOUND TRUE)
message(STATUS "Found ${PACKAGE_NAME}!")

set(${PACKAGE_NAME}_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/../../src/utils")
set(${PACKAGE_NAME}_INCLUDE_DIRS ${${PACKAGE_NAME}_SOURCE_DIR})
set(${PACKAGE_NAME}_SOURCES "")
set(${PACKAGE_NAME}_LIBS "")

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(${PACKAGE_NAME} REQUIRED_VARS ${PACKAGE_NAME}_FOUND)
